---
title: "Dirichlet-multinomial model"
date: '`r Sys.Date()`'
output: 
  html_document:
    keep_md: true
    self_contained: true
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

# Dirichlet-multinomial regression with covariates linked to mean

This is a repository for the work on a new Dirichlet-multinomial model.

## Simulations

### Strategy to simulate data from the Dirichlet-multinomial distribution

The Dirichlet-multinomial distribution is as follows.

$$
    \boldsymbol y_{i \cdot} | \boldsymbol\mu,\phi  \sim \mathcal{DM}(\boldsymbol\mu,\phi ) 
    = \binom{m}{(y_{i1},...,y_{iq})} \frac{\prod_{j=1}^q\prod_{k=1}^{y_{ij}}[\mu_j(1-\phi) + (k-1)\phi]}{\prod_{k=1}^m [1-\phi + (k-1)\phi]}.
$$

We can use the following algorithm to simulate Dirichlet-multinomial distributed data.

1. Set number of individuals $n$, number of total counts $m$ in every individual, proportions of $q$ categories $\boldsymbol\mu=(\mu_1,...,\mu_q)$, and dispersion parameter $\phi$.

2. Compute the Dirichlet's concentration parameters $\alpha_j=\mu_j (1-\phi) / \phi$, $j=1,...,q$.

3. Use gamma distribution to generate Dirichlet's probabilities of one individual:
    * For $j$-th category in $i$-th individual, generate $g_{ij} \sim Gamma(\alpha_j, 1)$, $j=1,...,q$.
    * Generate individual-specific compositional data $\mu_{ij} = g_{ij} / \sum_{j=1}^q g_{ij}$.
    * Repeat the two steps above for $i=1,...,n$ to generate data for $n$ individuals.

4. Generate each individual's counts $\boldsymbol y_{i\cdot} \sim Multinomial(m; \mu_{i1},...,\mu_{iq})$.
 

### Sim1: Simulation without covariates

```r
rm(list=ls())
# Load the function to simulate Dirichlet-multinomial distributed data
source("R/simDM.R")

#================================
# Simulate data without covariates
#================================
set.seed(123)
# Simulate two individuals with the same total counts 'mu' of each individual
Y1 <- simDM(n = 2, m = 100, mu = c(0.1, 0.5, 0.4), phi = 0.3)

# Simulate two individuals with different total counts 'mu'
Y2 <- simDM(n = 2, m = c(100, 120), mu = c(0.1, 0.5, 0.4), phi = 0.3)
```

### Sim2: Simulation with covariates linked to the mean

We can simualte Dirichlet-multinomial distributed responses with their mean modeled by covariates $\mathbf X$.

$$
    g_\mu (\mu_{ij}) = \mathbf X_i \boldsymbol\beta_j,
$$

where $g_\mu(\cdot)$ is the logit link functions. 


```r
rm(list=ls())
# Load the function to simulate Dirichlet-multinomial distributed data
source("R/simDM.R")

set.seed(123)
n <- 100
p <- 5
q <- 3

# simulate covariates X linked to DM's mean
X <- matrix(rnorm(n * p), nrow = n, ncol = p)
betas <- matrix(runif(p * q, -1, 1), nrow = p, ncol = q)
mu_all <- eta <- matrix(nrow = n, ncol = q)
for (j in 1:(q - 1)) {
  eta[, j] <- exp(X %*% betas[, j])
}
mu_all[, q] <- 1 / (1 + rowSums(eta[, -q]))
for (j in 1:(q - 1)) {
  mu_all[, j] <- eta[, j] / (1 + rowSums(eta[, -q]))
}

# simulate outcomes Y
Y <- matrix(nrow = n, ncol = q)
for (i in 1:n) {
  Y[i, ] <- simDM(n = 1, m = 100, mu = mu_all[i, ], phi = 0.1)
}

# estimate coefficients and dispersion parameters by optimizing log-likelihood function
source("R/target.R")
opt <- nlminb(
  start = c(rep(0.1, p * (q - 1)), 0.1),
  objective = loglikfun,
  lower = c(rep(-10, p * (q - 1)), 0.001),
  upper = c(rep(10, p * (q - 1)), 0.999)
)
(phi.hat <- opt$par[length(opt$par)])
```
```
## [1] 0.0928848
```

```r
# print out estimated coefficients
(betas.hat <- matrix(opt$par[-length(opt$par)], nrow = p))
```
```
##            [,1]       [,2]
## [1,] -0.4615551 -0.1884095
## [2,]  0.2017357  0.6039612
## [3,] -0.6522207 -0.3699939
## [4,]  0.8407859 -0.8557323
## [5,]  0.7880258 -0.1038670
```

```r
# print out true coefficients
betas[, -q]
```
```
##            [,1]        [,2]
## [1,] -0.4527545 -0.04422637
## [2,]  0.1877339  0.54738424
## [3,] -0.6796304 -0.40919984
## [4,]  0.7068605 -0.86874378
## [5,]  0.6954783 -0.11893375
```


### Sim3: Simulation with covariates linked to both mean and dispersion

We can simualte Dirichlet-multinomial distributed responses with their mean modeled by covariates $\mathbf X$ and their dispersion modeled by covariates $\mathbf Z$ as follows.

$$
\begin{aligned}
    g_\mu (\mu_{ij}) &= \mathbf X_i \boldsymbol\beta_j, \\
    %
    g_\phi (\phi_{i}) &= \mathbf Z_i \boldsymbol\gamma, 
\end{aligned}
$$

where $g_\mu(\cdot)$ and $g_\phi(\cdot)$ are both logit link functions. 
Note that the dispersion $\phi_i \in (0,1)$ and $\phi_i$ near $1$ might cause the simulation stopped due to only zero values generated from the gamma distribution. 
Therefore, we will use a trick (from Euloge) to tune the intercept $\gamma_0$ and control the mean of $\phi_i$ as a fixed value e.g. 0.2.

```r
set.seed(123)
n <- 100
p <- 5
q <- 3

# simulate covariates X linked to DM's mean
X <- matrix(rnorm(n * p), nrow = n, ncol = p)
betas <- matrix(runif(p * q, -1, 1), nrow = p, ncol = q)
mu_all <- eta <- matrix(nrow = n, ncol = q)
for (j in 1:(q - 1)) {
  eta[, j] <- exp(X %*% betas[, j])
}
mu_all[, q] <- 1 / (1 + rowSums(eta[, -q]))
for (j in 1:(q - 1)) {
  mu_all[, j] <- eta[, j] / (1 + rowSums(eta[, -q]))
}

# simulate covariates Z linked to DM's dispersion
# To be modified with logit link and control the prevalence with mean e.g. 0.2
set.seed(123)
p <- 1
#Z <- matrix(rnorm(n * p), nrow = n, ncol = p)
Z <- matrix(rbinom(100, 0:1, prob=c(0.5, 0.5)), nrow = n) # 
gammas <- runif(p, -1, 1)

# simulate outcomes Y
Y <- matrix(nrow = n, ncol = q)
for (i in 1:n) {
  Y[i, ] <- simDM(n = 1, m = 100, mu = mu_all[i, ], phi = phi_all[i])
}

head(Y)
```

```
##      [,1] [,2] [,3]
## [1,]    0    0  100
## [2,]    0   26   74
## [3,]    0   68   32
## [4,]    2   30   68
## [5,]    4   51   45
## [6,]    0    1   99
```
